//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Admin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adınız Soyadınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AdSoyad {
            get {
                return ResourceManager.GetString("AdSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anasayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What does this team member to? Keep it short! This is also a great spot for social links! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AnasayfaBirinciYazi {
            get {
                return ResourceManager.GetString("AnasayfaBirinciYazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What does this team member to? Keep it short! This is also a great spot for social links! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AnasayfaIkinciYazi {
            get {
                return ResourceManager.GetString("AnasayfaIkinciYazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   © 2018 BES Yazılım Şirketi. Tüm  Hakları Saklıdır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BESyazilim {
            get {
                return ResourceManager.GetString("BESyazilim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bize Yorum Yapın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BizeYorumYapin {
            get {
                return ResourceManager.GetString("BizeYorumYapin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bizim Takım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BizimTakim {
            get {
                return ResourceManager.GetString("BizimTakim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blog benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BlogKategori benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BlogKategori {
            get {
                return ResourceManager.GetString("BlogKategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detaylar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Detaylar {
            get {
                return ResourceManager.GetString("Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diğer Şubelerimiz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DigerSubeler {
            get {
                return ResourceManager.GetString("DigerSubeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duyurular benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Duyurular {
            get {
                return ResourceManager.GetString("Duyurular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   En Popüler 5 Blog benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string enPopulerBlog {
            get {
                return ResourceManager.GetString("enPopulerBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-Posta Adresiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Eposta {
            get {
                return ResourceManager.GetString("Eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etkinliklerimiz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Etkinlikler {
            get {
                return ResourceManager.GetString("Etkinlikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Gonder {
            get {
                return ResourceManager.GetString("Gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hakkımızda benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Harita benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Harita {
            get {
                return ResourceManager.GetString("Harita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İletişim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İletişim Formu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IletisimFormu {
            get {
                return ResourceManager.GetString("IletisimFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt Ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KayitOl {
            get {
                return ResourceManager.GetString("KayitOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KullaniciAdi {
            get {
                return ResourceManager.GetString("KullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yararlı Makaleler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string makale {
            get {
                return ResourceManager.GetString("makale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesajınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mesaj {
            get {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çalışmalarımız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Moduller {
            get {
                return ResourceManager.GetString("Moduller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturum Aç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OturumAc {
            get {
                return ResourceManager.GetString("OturumAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Kadromuz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PersonelKadrosu {
            get {
                return ResourceManager.GetString("PersonelKadrosu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Referanslar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Referanslar {
            get {
                return ResourceManager.GetString("Referanslar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sağlıklı Yaşam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string saglikliYasam {
            get {
                return ResourceManager.GetString("saglikliYasam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifrenizi Onaylayın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SifreOnay {
            get {
                return ResourceManager.GetString("SifreOnay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüm Duyurular  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TumDuyurular {
            get {
                return ResourceManager.GetString("TumDuyurular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yönetim Kadromuz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YonetimKadrosu {
            get {
                return ResourceManager.GetString("YonetimKadrosu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yorumlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Yorumlar {
            get {
                return ResourceManager.GetString("Yorumlar", resourceCulture);
            }
        }
    }
}
